import{a as q,i as n,S as w}from"./assets/vendor-b0d10f48.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function d(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=d(e);fetch(e.href,t)}})();const g=(r,s)=>q.get("https://pixabay.com/api/",{params:{key:"43795533-00e69c3734dde476e8d836fd2",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:"15"}}),h=r=>r.map(({webformatURL:d,largeImageURL:a,tags:e,likes:t,views:i,comments:L,downloads:b})=>`<a class="gallery-item" href="${a}">
        <img class="gallery-image" src="${d}" alt="${e}" />
        <div class="info">
           <p class="info-item"><span>Likes:</span> ${t}</p>
           <p class="info-item"><span>Views:</span> ${i}</p>
           <p class="info-item"><span>Comments:</span> ${L}</p>
           <p class="info-item"><span>Downloads:</span> ${b}</p>
         </div>
       </a>`).join(""),m=document.querySelector(".search-form"),u=document.querySelector(".gallery"),p=document.querySelector(".loader"),f=document.querySelector(".loader-more"),o=document.querySelector(".load-btn");let l=1,y=1,c="";m.addEventListener("submit",async r=>{if(r.preventDefault(),c=m.elements.query.value.trim(),!c){n.warning({title:"Warning",message:"Please fill out this field",position:"topRight"});return}o.classList.contains("is-active")&&o.classList.remove("is-active"),u.innerHTML="",p.classList.add("is-active"),l=1;try{const{data:s}=await g(c,l);if(!s.total){p.classList.remove("is-active"),n.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),m.reset();return}u.innerHTML=`${h(s.hits)}`,p.classList.remove("is-active"),o.classList.add("is-active"),s.totalHits<15&&(o.classList.remove("is-active"),n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})),v.refresh()}catch(s){console.log(s)}});o.addEventListener("click",async()=>{f.classList.add("is-active-more"),o.classList.remove("is-active");try{const{data:r}=await g(c,++l);u.insertAdjacentHTML("beforeend",`${h(r.hits)}`),f.classList.remove("is-active-more"),o.classList.add("is-active"),v.refresh(),window.scrollBy({top:720,behavior:"smooth"}),y=Math.ceil(r.totalHits/15),y===l&&(o.classList.remove("is-active"),n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch(r){console.log(r)}});const v=new w(".gallery a",{navText:["&#5176;","&#5171;"],captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
