import{a as q,i as a,S as w}from"./assets/vendor-b0d10f48.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function d(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=d(e);fetch(e.href,t)}})();const h=(r,s)=>q.get("https://pixabay.com/api/",{params:{key:"43795533-00e69c3734dde476e8d836fd2",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:"15"}}),y=r=>r.map(({webformatURL:d,largeImageURL:n,tags:e,likes:t,views:o,comments:L,downloads:b})=>`<a class="gallery-item" href="${n}">
        <img class="gallery-image" src="${d}" alt="${e}" />
        <div class="info">
           <p class="info-item"><span>Likes:</span> ${t}</p>
           <p class="info-item"><span>Views:</span> ${o}</p>
           <p class="info-item"><span>Comments:</span> ${L}</p>
           <p class="info-item"><span>Downloads:</span> ${b}</p>
         </div>
       </a>`).join(""),m=document.querySelector(".search-form"),u=document.querySelector(".gallery"),p=document.querySelector(".loader"),f=document.querySelector(".loader-more"),i=document.querySelector(".load-btn");let l=1,g=1,c="";m.addEventListener("submit",async r=>{if(r.preventDefault(),c=m.elements.query.value.trim(),!c){a.warning({title:"Warning",message:"Please fill out this field",position:"topRight"});return}i.classList.contains("is-active")&&i.classList.remove("is-active"),u.innerHTML="",p.classList.add("is-active"),l=1;try{const{data:s}=await h(c,l);if(!s.total){p.classList.remove("is-active"),a.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),m.reset();return}u.innerHTML=`${y(s.hits)}`,p.classList.remove("is-active"),i.classList.add("is-active"),s.totalHits<15&&(i.classList.remove("is-active"),a.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})),v.refresh()}catch{a.error({position:"topRight",message:"Error fetching images. Please try again later."})}});i.addEventListener("click",async()=>{f.classList.add("is-active-more"),i.classList.remove("is-active");try{const{data:r}=await h(c,++l);u.insertAdjacentHTML("beforeend",`${y(r.hits)}`),f.classList.remove("is-active-more"),i.classList.add("is-active"),v.refresh(),window.scrollBy({top:720,behavior:"smooth"}),g=Math.ceil(r.totalHits/15),g===l&&(i.classList.remove("is-active"),a.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({position:"topRight",message:"Error fetching images. Please try again later."})}});const v=new w(".gallery a",{navText:["&#5176;","&#5171;"],captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
