import{a as h,S as y,i as a}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const m="44100586-6dae9d5f9d68e136096a0f58f",g="https://pixabay.com/api/";async function u(r,o){const s=new URLSearchParams({key:m,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15});try{return(await h.get(`${g}?${s}`)).data}catch(n){console.error(n)}}function d(r){const o=document.querySelector(".gallery"),s=r.map(e=>`
      <a class="gallery-item" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <p class="info-item"><span>Likes:</span> ${e.likes}</p>
          <p class="info-item"><span>Views:</span> ${e.views}</p>
          <p class="info-item"><span>Comments:</span> ${e.comments}</p>
          <p class="info-item"><span>Downloads:</span> ${e.downloads}</p>
        </div>
      </a>`).join("");o.innerHTML=s,new y(".gallery a",{navText:["&#5176;","&#5171;"],captionsData:"alt",captionDelay:250}).refresh()}function L(){const r=document.querySelector(".gallery");r.innerHTML=""}const S=document.querySelector(".search-form"),b=document.querySelector(".search-input");document.querySelector(".gallery");const p=document.querySelector(".loader"),i=document.querySelector("#load-btn");let c=1,q="";S.addEventListener("submit",v);function v(r){r.preventDefault(),c=1;const o=b.value.trim();if(o===""){a.error({title:"Error",message:"Please enter a search query"});return}L(),$(),u(o,c).then(s=>{s.hits.length===0&&a.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again."}),d(s.hits),s.hits.length===15&&i.classList.remove(".hidden")}).catch(s=>{a.error({position:"topRight",message:"Error"})}).finally(()=>{f()})}i.addEventListener("click",w);async function w(){c+=1;try{const r=await u(q,c);if(r.hits.length===0){a.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),i.classList.add("hidden");return}d(r.hits),r.hits.length<15&&i.classList.add("hidden"),window.scrollBy({top:720,behavior:"smooth"})}catch{a.error({position:"topRight",message:"Error"})}finally{f()}}function $(){p.style.display="block"}function f(){p.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
